# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# SPDX-License-Identifier: BSD-3-Clause

"""Generate runtime artifacts from the single authored deployment catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from .catalog import DeploymentCatalog, load_catalog, monorepo_root


def runtime_catalog_path() -> Path:
    return (
        monorepo_root()
        / "Unity_XRPlayground"
        / "Assets"
        / "Resources"
        / "XRPlayground"
        / "stations.json"
    )


def documentation_path() -> Path:
    return monorepo_root() / "deployment" / "STATIONS.generated.md"


def render_runtime_catalog(catalog: DeploymentCatalog) -> str:
    return json.dumps(catalog.to_runtime_dict(), indent=2, sort_keys=True) + "\n"


def render_documentation(catalog: DeploymentCatalog) -> str:
    lines = [
        "# Deployment Stations (generated)",
        "",
        "> Generated from `deployment/stations.json`. Do not edit this file directly.",
        "",
        "| Station | Robot | Adapter | Port | Policies | Physics / policy |",
        "|---|---|---|---:|---|---|",
    ]
    for station in catalog.stations:
        policies = [catalog.policy(policy_id) for policy_id in station.policy_ids]
        cadence = ", ".join(
            f"{policy.deployment_physics_hz}/{policy.policy_hz} Hz" for policy in policies
        )
        lines.append(
            f"| {station.display_name} (`{station.station_id}`) | `{station.robot_id}` | "
            f"`{station.adapter_id}` | {station.port} | "
            f"{', '.join(f'`{item.policy_id}`' for item in policies)} | {cadence} |"
        )
    lines.extend(
        [
            "",
            "## Policy contracts",
            "",
            "| Policy ID | Isaac task | Observation -> action | Metric | Unity gate | Task thresholds |",
            "|---|---|---:|---|---:|---|",
        ]
    )
    for policy in catalog.policies:
        thresholds = ", ".join(
            f"`{item['metric']} {item['comparison']} {float(item['value']):g}`"
            for item in policy.task_thresholds
        )
        lines.append(
            f"| `{policy.policy_id}` | `{policy.source_task_id}` | "
            f"{policy.observation_dim} -> {policy.action_dim} | `{policy.primary_metric}` | "
            f"{policy.minimum_unity_relative_score:.0%} of Isaac | {thresholds} |"
        )
    lines.extend(
        [
            "",
            "## Robot asset provenance",
            "",
            "| Robot ID | Redistribution | License | Provenance |",
            "|---|---|---|---|",
        ]
    )
    for asset in catalog.robot_assets:
        status = "verified" if asset.redistribution_verified else "blocked"
        lines.append(
            f"| `{asset.robot_id}` | {status} | `{asset.redistribution_license}` | "
            f"{asset.provenance} |"
        )
    return "\n".join(lines) + "\n"


def generate(*, check: bool = False) -> list[Path]:
    catalog = load_catalog()
    artifacts = {
        runtime_catalog_path(): render_runtime_catalog(catalog),
        documentation_path(): render_documentation(catalog),
    }
    changed: list[Path] = []
    for path, content in artifacts.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        changed.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if check and changed:
        paths = "\n".join(f"  - {path}" for path in changed)
        raise RuntimeError(f"Generated deployment artifacts are stale:\n{paths}")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated files differ")
    args = parser.parse_args(argv)
    try:
        changed = generate(check=args.check)
    except RuntimeError as exc:
        parser.error(str(exc))
    if changed:
        print("Updated " + ", ".join(str(path) for path in changed))
    else:
        print("Deployment artifacts are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
